name: Build and deploy Node.js app to Azure Web App - intan-blockchain-explorer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install pnpm
        run: npm install -g pnpm@8.1.0
        
      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build:pro 
      
      # Only upload the build directory
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./dist-pro # Replace with the correct path to your build output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: List files in the working directory
        run: ls -R
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1685DC4F543D4CDB8589FCAFE63E9E28 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_21D8356B1813483AB29F934F95396A35 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D6D5CC5848684800B468B7D57794E80C }} 

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'explorer-server-1'
          slot-name: 'Production'
          package: .
